const ASSET_BASE = import.meta.env.BASE_URL;

export const albums = [
  {
    id: 1,
    title: "Momo's Private School",
    year: "July 31, 2020",
    tracks: 14,
    genre: "Amapiano",
    streams: "30,561,937",
    image: `${ASSET_BASE}albums/album-1.jpg`,
    url: "https://open.spotify.com/album/2iMSucuLkRpTalT9BPkdM5",
  },
  {
    id: 2,
    title: "Ivy League",
    year: "December 17, 2021",
    tracks: 21,
    genre: "Amapiano",
    streams: "45,995,695",
    image: `${ASSET_BASE}albums/album-2.webp`,
    url: "https://open.spotify.com/album/3H2eycTSwpPa0mGpacbyn6",
  },
  {
    id: 3,
    title: "Amukelani",
    year: "December 9, 2022",
    tracks: 26,
    genre: "Amapiano",
    streams: "88,720,213",
    image: `${ASSET_BASE}albums/album-3.jpg`,
    url: "https://open.spotify.com/album/7LZDrSxVlyIXv2tVKmB5Nf",
  },
  {
    id: 4,
    title: "Kurhula",
    year: "December 8, 2023",
    tracks: 27,
    genre: "Amapiano",
    streams: "76,085,247",
    image: `${ASSET_BASE}albums/album-4.jpg`,
    url: "https://open.spotify.com/album/13msT9b5VOsDENyqMX7V1c",
  },
  {
    id: 5,
    title: "Sewe",
    year: "August 9, 2024",
    tracks: 30,
    genre: "Amapiano",
    streams: "36,703,015",
    image: `${ASSET_BASE}albums/album-5.jpg`,
    url: "https://open.spotify.com/album/3q8j0FIXu60xJIzeDrqOzh",
  },
  {
    id: 6,
    title: "Ntsako",
    year: "December 13, 2024",
    tracks: 24,
    genre: "Amapiano",
    streams: "67,174,708",
    image: `${ASSET_BASE}albums/album-6.jpg`,
    url: "https://open.spotify.com/album/7tqEXec8u8dGBRYhk5m4LU",
  },
  {
    id: 7,
    title: "Thato Ya Modimo",
    year: "May 30, 2025",
    tracks: 29,
    genre: "Amapiano",
    streams: "49,090,446",
    image: `${ASSET_BASE}albums/album-7.jpg`,
    url: "https://open.spotify.com/album/2kVTT41hC7qiYIOEoENEBY",
  },
  {
    id: 8,
    title: "N'wana Wa Mutsonga",
    year: "December 12, 2025",
    tracks: 31,
    genre: "Amapiano",
    streams: "15,347,018",
    image: `${ASSET_BASE}albums/album-8.jpg`,
    url: "https://open.spotify.com/album/7ndjK6cXU4fVdxlVXU9C4b",
  },
];

export const tourDates = [
  {
    id: 1,
    date: "2026-02-27",
    city: "Cape Town",
    country: "South Africa",
    venue: "Cabo Beach Club",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Cabo Beach Club debut performance",
  },
  {
    id: 2,
    date: "2026-03-14",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Puma Social Club",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Intimate club experience",
  },
  {
    id: 3,
    date: "2026-03-21",
    city: "Pretoria",
    country: "South Africa",
    venue: "The Sun Arena at Time Square",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 4,
    date: "2026-03-28",
    city: "Durban",
    country: "South Africa",
    venue: "The WaveHouse",
    status: "few-left",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Beachfront venue special"
  },
  {
    id: 5,
    date: "2026-04-05",
    city: "Durban",
    country: "South Africa",
    venue: "Moses Mabhida Stadium People's Park",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "One Man Concert - Durban Tourism & Don Julio present",
  },
  {
    id: 6,
    date: "2026-04-11",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Carfax",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 7,
    date: "2026-04-18",
    city: "Cape Town",
    country: "South Africa",
    venue: "The Grand Africa CafÃ© & Beach",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 8,
    date: "2026-04-25",
    city: "Cape Town",
    country: "South Africa",
    venue: "CTICC (Cape Town International Convention Centre)",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Cape Town International Jazz Festival",
  },
  {
    id: 9,
    date: "2026-04-26",
    city: "Cape Town",
    country: "South Africa",
    venue: "CTICC (Cape Town International Convention Centre)",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Cape Town International Jazz Festival - Day 2",
  },
  {
    id: 10,
    date: "2026-05-02",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Zone 6 Venue",
    status: "few-left",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 11,
    date: "2026-05-09",
    city: "Soweto",
    country: "South Africa",
    venue: "Constitutional Hill",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 12,
    date: "2026-05-16",
    city: "Pretoria",
    country: "South Africa",
    venue: "The Pyramid Venue",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 13,
    date: "2026-05-23",
    city: "Durban",
    country: "South Africa",
    venue: "The Chairman",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 14,
    date: "2026-05-30",
    city: "Johannesburg",
    country: "South Africa",
    venue: "And Club",
    status: "few-left",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 15,
    date: "2026-06-06",
    city: "Cape Town",
    country: "South Africa",
    venue: "The Village Lounge",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 16,
    date: "2026-06-13",
    city: "Johannesburg",
    country: "South Africa",
    venue: "The Living Room",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 17,
    date: "2026-06-20",
    city: "Soweto",
    country: "South Africa",
    venue: "The Soweto Theatre",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Special acoustic set",
  },
  {
    id: 18,
    date: "2026-06-27",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Puma Social Club",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Final show of South African leg",
  },
];

export const merchItems = [
  {
    id: 1,
    name: "Private School Hoodie",
    image: `${ASSET_BASE}merchs/African Giant Anniversary T-Shirt.webp`,
    price: "R1,250",
    originalPrice: "R1,500",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 2,
    name: "Momo Cup",
    image: `${ASSET_BASE}merchs/del/I told them... Fan Pack.webp`,
    price: "R650",
    category: "Accessories",
  },
  {
    id: 3,
    name: "Signature Fleece",
    image: `${ASSET_BASE}merchs/African Giant Anniversary T-Shirt.webp`,
    price: "R1,350",
    category: "Apparel",
    limited: true,
  },
  {
    id: 4,
    name: "Baggy Trackie Set",
    image: `${ASSET_BASE}merchs/del/I told them... T-Shirt.webp`,
    price: "R1,450",
    originalPrice: "R1,500",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 5,
    name: "Tour Graphic Hoodie",
    image: `${ASSET_BASE}merchs/del/Love, Damini Tee.webp`,
    price: "R1,100",
    category: "Apparel",
  },
  {
    id: 6,
    name: "Minimalist Fleece",
    image: `${ASSET_BASE}merchs/del/I told them... Vinyl.webp`,
    price: "R980",
    category: "Apparel",
  },
  {
    id: 7,
    name: "Private School Trackie Pants",
    image: `${ASSET_BASE}merchs/del/Twice As Tall Exclusive Red Vinyl.webp`,
    price: "R890",
    category: "Apparel",
  },
  {
    id: 8,
    name: "Momo Cup Deluxe",
    image: `${ASSET_BASE}merchs/del/Twice As Tall T-Shirt(Black).webp`,
    price: "R780",
    category: "Accessories",
    limited: true,
  },
  {
    id: 9,
    name: "Oversized Fleece Hoodie",
    image: `${ASSET_BASE}merchs/del/No Sign Of Weakness Vinyl.webp`,
    price: "R1,300",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 10,
    name: "Baggy Trackie Jacket",
    image: `${ASSET_BASE}merchs/del/Love, Damini Vinyl.webp`,
    price: "R1,200",
    category: "Apparel",
  },
];
