export const albums = [
  {
    id: 1,
    title: "L.I.F.E",
    year: "August 12, 2013",
    tracks: 17,
    genre: "Afrobeat, Ragga, Dancehall, Fuji",
    streams: "37 M",
    image: "/albums/album-1.jpg",
    url: "https://open.spotify.com/album/7pqUKMWH6P7AJPIjUiphTS",
  },
  {
    id: 2,
    title: "On a Spaceship",
    year: "November 16, 2015",
    tracks: 14,
    genre: "Afrobeats, Afro-fusion",
    streams: "42.8 M",
    image: "/albums/album-2.webp",
    url: "https://open.spotify.com/album/5zH79s5J4D633IxoFWadp8",
  },
  {
    id: 3,
    title: "Outside",
    year: "January 26, 2018",
    tracks: 15,
    genre: "Afrobeats, Reggae, Dancehall",
    streams: "430 M",
    image: "/albums/album-3.jpg",
    url: "https://open.spotify.com/album/5SCK5p3Rqgg0FwTmAurrcp",
  },
  {
    id: 4,
    title: "African Giant",
    year: "July 26, 2019",
    tracks: 17,
    genre: "Afrobeats, Dancehall, Pop, Hip-hop",
    streams: "1.114 B",
    image: "/albums/album-4.jpg",
    url: "https://open.spotify.com/album/79lrrUvUyIuOD12b5taQVP",
  },
  {
    id: 5,
    title: "Twice as Tall",
    year: "August 14, 2020",
    tracks: 14,
    genre: "Afrobeats, Dancehall, Pop, Hip-hop",
    streams: "357.4 M",
    image: "/albums/album-5.jpg",
    url: "https://open.spotify.com/album/4moiYbxseWbPD2moVhOYje",
  },
  {
    id: 6,
    title: "Love, Damini",
    year: "July 8, 2022",
    tracks: 16,
    genre: "Afro-fusion",
    streams: "1.435 B",
    image: "/albums/album-6.jpg",
    url: "https://open.spotify.com/album/6kgDkAupBVRSqbJPUaTJwQ",
  },
  {
    id: 7,
    title: "I Told Them...",
    year: "August 25, 2023",
    tracks: 13,
    genre: "Afro-fusion, Afrobeats, Hip-hop",
    streams: "701.5 M",
    image: "/albums/album-7.jpg",
    url: "https://open.spotify.com/album/1JzjwUKkPsdHg1SQ7qa5hc",
  },
  {
    id: 8,
    title: "No Sign of Weakness",
    year: "July 11, 2025",
    tracks: 16,
    genre: "Afrobeats, Rock, Funk, Country, Electronic",
    streams: "134.6 M",
    image: "/albums/album-8.jpg",
    url: "https://open.spotify.com/album/35EMM8QwKJ2qXmoUJnUSNf",
  },
];

export const tourDates = [
  {
    id: 1,
    date: "2026-02-27",
    city: "Cape Town",
    country: "South Africa",
    venue: "Cabo Beach Club",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Cabo Beach Club debut performance",
  },
  {
    id: 2,
    date: "2026-03-14",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Puma Social Club",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Intimate club experience",
  },
  {
    id: 3,
    date: "2026-03-21",
    city: "Pretoria",
    country: "South Africa",
    venue: "The Sun Arena at Time Square",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 4,
    date: "2026-03-28",
    city: "Durban",
    country: "South Africa",
    venue: "The WaveHouse",
    status: "few-left",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Beachfront venue special"
  },
  {
    id: 5,
    date: "2026-04-05",
    city: "Durban",
    country: "South Africa",
    venue: "Moses Mabhida Stadium People's Park",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "One Man Concert - Durban Tourism & Don Julio present",
  },
  {
    id: 6,
    date: "2026-04-11",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Carfax",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 7,
    date: "2026-04-18",
    city: "Cape Town",
    country: "South Africa",
    venue: "The Grand Africa Café & Beach",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 8,
    date: "2026-04-25",
    city: "Cape Town",
    country: "South Africa",
    venue: "CTICC (Cape Town International Convention Centre)",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Cape Town International Jazz Festival",
  },
  {
    id: 9,
    date: "2026-04-26",
    city: "Cape Town",
    country: "South Africa",
    venue: "CTICC (Cape Town International Convention Centre)",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Cape Town International Jazz Festival - Day 2",
  },
  {
    id: 10,
    date: "2026-05-02",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Zone 6 Venue",
    status: "few-left",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 11,
    date: "2026-05-09",
    city: "Soweto",
    country: "South Africa",
    venue: "Constitutional Hill",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 12,
    date: "2026-05-16",
    city: "Pretoria",
    country: "South Africa",
    venue: "The Pyramid Venue",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 13,
    date: "2026-05-23",
    city: "Durban",
    country: "South Africa",
    venue: "The Chairman",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 14,
    date: "2026-05-30",
    city: "Johannesburg",
    country: "South Africa",
    venue: "And Club",
    status: "few-left",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 15,
    date: "2026-06-06",
    city: "Cape Town",
    country: "South Africa",
    venue: "The Village Lounge",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 16,
    date: "2026-06-13",
    city: "Johannesburg",
    country: "South Africa",
    venue: "The Living Room",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
  },
  {
    id: 17,
    date: "2026-06-20",
    city: "Soweto",
    country: "South Africa",
    venue: "The Soweto Theatre",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Special acoustic set",
  },
  {
    id: 18,
    date: "2026-06-27",
    city: "Johannesburg",
    country: "South Africa",
    venue: "Puma Social Club",
    status: "available",
    ticketUrl: "https://www.webtickets.co.za/v2/event.aspx?itemid=1588872108",
    special: "Final show of South African leg",
  },
];

export const merchItems = [
  {
    id: 1,
    name: "African Giant Anniversary T-Shirt",
    image: "/merchs/African Giant Anniversary T-Shirt.webp",
    price: "₦12,000",
    originalPrice: "₦15,000",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 2,
    name: "I Told Them... Fan Pack",
    image: "/merchs/I told them... Fan Pack.webp",
    price: "₦7,000",
    category: "Accessories",
  },
  {
    id: 3,
    name: "African Giant Anniversary T-Shirt",
    image: "/merchs/African Giant Anniversary T-Shirt.webp",
    price: "₦25,000",
    category: "Apparel",
    limited: true,
  },
  {
    id: 4,
    name: "I told them... T-Shirt",
    image: "/merchs/I told them... T-Shirt.webp",
    price: "₦18,000",
    originalPrice: "₦22,000",
    category: "Apparel",
    bestseller: true,
  },
  {
    id: 5,
    name: "Love, Damini Tee",
    image: "/merchs/Love, Damini Tee.webp",
    price: "₦4,500",
    category: "Apparel",
  },
  {
    id: 6,
    name: "I told them... Vinyl",
    image: "/merchs/I told them... Vinyl.webp",
    price: "₦3,000",
    category: "Art",
  },
  {
    id: 7,
    name: "Twice As Tall Exclusive Red Vinyl",
    image: "/merchs/Twice As Tall Exclusive Red Vinyl.webp",
    price: "₦6,500",
    category: "Art",
  },
  {
    id: 8,
    name: "Twice As Tall T-Shirt(Black)",
    image: "/merchs/Twice As Tall T-Shirt(Black).webp",
    price: "₦8,000",
    category: "Accessories",
    limited: true,
  },
  {
    id: 9,
    name: "No Sign Of Weakness Vinyl",
    image: "/merchs/No Sign Of Weakness Vinyl.webp",
    price: "₦8,000",
    category: "Art",
    bestseller: true,
  },
  {
    id: 10,
    name: "Love, Damini Vinyl",
    image: "/merchs/Love, Damini Vinyl.webp",
    price: "₦8,000",
    category: "Art",
  },
];